### ISSUE TITLE
[Noob Question] Regarding Context/Tokens in Documents

### ISSUE THREAD

**Issue by init27** [nelson-liu/lost-in-the-middle#1]
Hello!

First of all, thank you for the amazing research work! I have read the paper at least 3 times and really enjoyed learning from your observations. 

I had a really dumb question about the length of the documents being used for Q&A, I downloaded a document sample from the folder and found that these have >1M tokens. 

I believe I might be missing something obvious-Could you please point me to the correct way of checking the same? My goal is to find out the average length of tokens being used for the evaluations. 

Thanks again for the amazing work!

**Comment by nelson-liu** [comment]
Hi Sanyam, thanks for the kind words! Properly counting the lengths of the input contexts requires taking the documents and formatting them as prompts. I'm hoping to add some code to make that easier, but it might be a bit as I'm traveling.

We're also planning on putting up an updated version of the paper with token counts for each of the models and each of the settings---we rarely mention token counts in the paper because it can be pretty tough to compare between models. Haven't had the time to properly format this big latex table, but here's a google sheet with the counts if you're interested: https://docs.google.com/spreadsheets/d/1loqrM4k8whMDXr5o0VXFIY-yZjAClAsz1SHev-Gfesg/edit?usp=sharing
