### ISSUE TITLE
Reasons for calculating accuracy in the manner of this work

### ISSUE THREAD

**Issue by JiaangL** [nelson-liu/lost-in-the-middle#10]
Hi, thanks for this nice work! The observations are really interesting and inspiring. 

I have some questions about the way to compute accuracy. I have read #2, which suggests that this work computes max accuracy of any token span of the prediction. I would appreciate it if you could share the reasons for doing so. Or could you share some previous works that also report this metric? Because the works I saw before [1] reported different metrics, like EM or F1. The precision in F1 is determined by considering the number of overlaps with all predicted tokens, which is different from the way to compute accuracy in this work.  

Thank you for your time!

[1] Investigating the Factual Knowledge Boundary of Large Language Models with Retrieval Augmentation.

**Comment by nelson-liu** [comment]
Hi @JiaangL , thanks for your interest. some thoughts inline:

(answering this first, since I think it's easiest to explain the choice of metric through this alternative): 

> I would appreciate it if you could share the reasons for doing so.
> Because the works I saw before [1] reported different metrics, like EM or F1. The precision in F1 is determined by considering the number of overlaps with all predicted tokens, which is different from the way to compute accuracy in this work.

It looks like this paper came out after ours (July 6 vs. July 20), sorry for missing it. From a first read, it looks like they're doing the standard SQuAD / NQ-Open-style EM / F1 evaluation. In SQuAD / NQ-Open, the answers are _shortform_---you get a phrase / a few words as your gold answer. Accordingly, in the work you linked, they prompted to model to produce a shortform response (Figure 1; "Answer the following question with one or few words ..."). This makes it straightforward to use the standard SQuAD / NQ metrics, since the output answer / gold answer are both shortform.

Personally, I think it's a bit more natural to elicit a long-form response from the model, since getting such a short-form response from prompting can be hard for models that, e.g., aren't instruction-tuned (this is not a problem for `text-davinci-003` / `gpt-3.5-turbo`, which are the models considered by the paper you linked).

However, you can't just directly apply the standard SQuAD EM / F1 to the longform generated answer---EM will always be 0, and token overlap will always be low, simply because the longform generated answer is much longer than the shortform answer. E.g., suppose the gold answer is 'John Smith' and the model generates 'Given the evidence above, the answer is John Smith'. EM is clearly 0, and F1 would be low because there's low token overlap between the strings. As a result, we chose to check for the presence of the shortform gold answer in the longform generated answer (max subspan EM). You could also think about doing the max F1 between the shortform gold and any span in the longform generated answer.

However, note that at the end of the day, these are all proxies for human eval---if I had infinite budget, the metric i'd trust would be to hire human annotators (or use GPT-4) to evaluate whether a shortform answer is entailed by the longform generated answer. [Evaluating Open-Domain Question Answering in the Era of Large Language Models](https://arxiv.org/abs/2305.06984) has some nice discussion / experimentation about how various proxies compare to this human eval gold.

> Or could you share some previous works that also report this metric?

Sure, here are other papers that report this metric (under different names):
- [When Not to Trust Language Models: Investigating Effectiveness of Parametric and Non-Parametric Memories](https://arxiv.org/abs/2212.10511)  (see section 3).
- [Enabling Large Language Models to Generate Text with Citations](https://arxiv.org/abs/2305.14627)  (see section 3.2, "EM recall").
  - they cite [ASQA: Factoid Questions Meet Long-Form Answers](https://arxiv.org/abs/2204.06092) as the source for this metric.

There are probably more, but this is what comes to mind immediately.

Hope that helps! I'll close this issue for now, but feel free to re-open / follow up.

**Comment by JiaangL** [comment]
Thanks so much for the detailed response! That's very helpful.
