### ISSUE TITLE
Script to retrieve passages given query?

### ISSUE THREAD

**Issue by LorrinWWW** [nelson-liu/lost-in-the-middle#4]
Thank you for sharing the excellent work! Do you have any plan to release the script to retrieve documents for nq, i.e. this file [nq-open-contriever-msmarco-retrieved-documents.jsonl.gz](https://nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-contriever-msmarco-retrieved-documents.jsonl.gz)? 
Thank you again!

**Comment by LorrinWWW** [comment]
Btw, is the qa data the validation (sub)set of [natural questions](https://ai.google.com/research/NaturalQuestions)? 🙏

**Comment by nelson-liu** [comment]
> Do you have any plan to release the script to retrieve documents for nq, i.e. this file nq-open-contriever-msmarco-retrieved-documents.jsonl.gz? 

I don't have any plans to share that script, since I  basically just ran the code in https://github.com/facebookresearch/contriever#question-answering-retrieval . Maybe try that and let me know if it doesn't work well for you?

> Btw, is the qa data the validation (sub)set of natural questions? pray

Hmm, so the QA data is a subset of the NQ-Open test split, which itself is a subset of the original NQ validation data, I believe.

Feel free to re-open if you have follow-up questions, but I'm going to close this for now.

**Comment by LorrinWWW** [comment]
I see, thank you!
