### ISSUE TITLE
less question number than original NQ-Open data

### ISSUE THREAD

**Issue by zmzhang2000** [nelson-liu/lost-in-the-middle#9]
Thank you for the intuitive work and the released code.

I wonder why there are only 2655 questions in the test data. The original NQ-Open testset has 3610 question totally as far as I know. Could you share more details about data filtering?

**Comment by nelson-liu** [comment]
Hi @zmzhang2000 , you're correct, the original NQ open data has 3610 questions. However, the "gold" evidence (as annotated in NQ) for some of those questions come from tables, lists, and other non-paragraph elements. To be concrete:

As far as I can tell, the original NQ-open was created by taking all NQ questions that:
- (1) have a short answer (and thus have a long answer)
- (2) the short answer is 5 words or less

We add the additional filter of:
- (3) the short answer / long answer comes from a paragraph (as opposed to a list or table)

We add this because our retrieval corpus (the 100-chunk wikipedia used by a bunch of prior work) only includes paragraphs, so we accordingly removed all questions where the gold evidence wasn't a paragraph.

Let me know if that answers your question! I'll close this for now, but feel free to follow up.
